modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/CodeOfArdonia/Throwable/issues"
license = "All Right Reserved"

[[mods]]
modId = "throwable"
version = "${version}"
displayName = "Throwable"
authors = "IAFEnvoy"
description = '''
Throw everything!
'''
logoFile = "logo.png"

[[dependencies.throwable]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.throwable]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"
