modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/CodeOfArdonia/Throwable/issues"
license = "All Right Reserved"

[[mods]]
modId = "throwable"
version = "${version}"
displayName = "Throwable"
authors = "IAFEnvoy"
description = '''
Throw everything!
'''
logoFile = "logo.png"

[[dependencies.throwable]]
modId = "neoforge"
mandatory = true
versionRange = "[2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.throwable]]
modId = "minecraft"
mandatory = true
versionRange = "[1.21,1.21.2)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "throwable.mixins.json"